// This file is automatically generated

#if UNITY_STANDALONE_OSX
#    error GL is not active! Please, activate it in Tools -> NoesisGUI -> Settings
#endif
#if UNITY_IPHONE
#    error iOS is not active! Please, activate it in Tools -> NoesisGUI -> Settings
#endif
