/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

namespace Noesis
{

public class ManipulationInertiaStartingEventArgs : RoutedEventArgs {
  private HandleRef swigCPtr;

  internal ManipulationInertiaStartingEventArgs(IntPtr cPtr, bool cMemoryOwn) : base(NoesisGUI_PINVOKE.ManipulationInertiaStartingEventArgs_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(ManipulationInertiaStartingEventArgs obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~ManipulationInertiaStartingEventArgs() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          if (Noesis.Extend.Initialized) { NoesisGUI_PINVOKE.delete_ManipulationInertiaStartingEventArgs(swigCPtr);}
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public Noesis.UIElement ManipulationContainer {
    get {
      return GetManipulationContainerHelper();
    }
  }

  public Noesis.Point ManipulationOrigin {
    get {
      return GetManipulationOriginHelper();
    }
    set {
      SetManipulationOriginHelper(value);
    }
  }

  public Noesis.ManipulationVelocities InitialVelocities {
    get {
      return GetInitialVelocitiesHelper();
    }
  }

  public float ExpansionBehavior {
    get {
      return GetExpansionBehaviorHelper();
    }
    set {
      SetExpansionBehaviorHelper(value);
    }
  }

  public float TranslationBehavior {
    get {
      return GetTranslationBehaviorHelper();
    }
    set {
      SetTranslationBehaviorHelper(value);
    }
  }

  public float RotationBehavior {
    get {
      return GetRotationBehaviorHelper();
    }
    set {
      SetRotationBehaviorHelper(value);
    }
  }

  public ManipulationInertiaStartingEventArgs(object s, RoutedEvent e, Visual manipulationContainer, Point manipulationOrigin, ManipulationVelocities initialVelocities) : this(NoesisGUI_PINVOKE.new_ManipulationInertiaStartingEventArgs(Noesis.Extend.GetInstanceHandle(s), RoutedEvent.getCPtr(e), Visual.getCPtr(manipulationContainer), ref manipulationOrigin, ManipulationVelocities.getCPtr(initialVelocities)), true) {
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
  }

  public bool Cancel() {
    bool ret = NoesisGUI_PINVOKE.ManipulationInertiaStartingEventArgs_Cancel(swigCPtr);
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
    return ret;
  }

  private UIElement GetManipulationContainerHelper() {
    IntPtr cPtr = NoesisGUI_PINVOKE.ManipulationInertiaStartingEventArgs_GetManipulationContainerHelper(swigCPtr);
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
    return Noesis.Extend.GetProxy(cPtr, false) as UIElement;
  }

  private Point GetManipulationOriginHelper() {
    IntPtr ret = NoesisGUI_PINVOKE.ManipulationInertiaStartingEventArgs_GetManipulationOriginHelper(swigCPtr);
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
    if (ret != IntPtr.Zero) {
      return Marshal.PtrToStructure<Point>(ret);
    }
    else {
      return new Point();
    }
  }

  private void SetManipulationOriginHelper(Point origin) {
    NoesisGUI_PINVOKE.ManipulationInertiaStartingEventArgs_SetManipulationOriginHelper(swigCPtr, ref origin);
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
  }

  private ManipulationVelocities GetInitialVelocitiesHelper() {
    ManipulationVelocities ret = new ManipulationVelocities(NoesisGUI_PINVOKE.ManipulationInertiaStartingEventArgs_GetInitialVelocitiesHelper(swigCPtr), true);
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
    return ret;
  }

  private float GetExpansionBehaviorHelper() {
    float ret = NoesisGUI_PINVOKE.ManipulationInertiaStartingEventArgs_GetExpansionBehaviorHelper(swigCPtr);
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
    return ret;
  }

  private void SetExpansionBehaviorHelper(float rate) {
    NoesisGUI_PINVOKE.ManipulationInertiaStartingEventArgs_SetExpansionBehaviorHelper(swigCPtr, rate);
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
  }

  private float GetTranslationBehaviorHelper() {
    float ret = NoesisGUI_PINVOKE.ManipulationInertiaStartingEventArgs_GetTranslationBehaviorHelper(swigCPtr);
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
    return ret;
  }

  private void SetTranslationBehaviorHelper(float rate) {
    NoesisGUI_PINVOKE.ManipulationInertiaStartingEventArgs_SetTranslationBehaviorHelper(swigCPtr, rate);
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
  }

  private float GetRotationBehaviorHelper() {
    float ret = NoesisGUI_PINVOKE.ManipulationInertiaStartingEventArgs_GetRotationBehaviorHelper(swigCPtr);
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
    return ret;
  }

  private void SetRotationBehaviorHelper(float rate) {
    NoesisGUI_PINVOKE.ManipulationInertiaStartingEventArgs_SetRotationBehaviorHelper(swigCPtr, rate);
    #if UNITY_EDITOR || NOESIS_API
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    #endif
  }

}

}

